# Generated by Django 4.1.3 on 2022-12-14 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=1000)),
                ('project_description', models.CharField(max_length=5000)),
                ('project_status', models.CharField(choices=[('Cancelled', 'CANCELLED'), ('Completed', 'COMPLETED'), ('In Progress', 'IN PROGRESS'), ('Not Started', 'NOT STARTED'), ('On Hold', 'ON HOLD'), ('Past Due', 'PAST DUE')], max_length=55)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('started_on', models.DateField()),
                ('completion_date', models.DateField()),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
